name: Compilar APK de Jarvis
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalar dependencias
        run: npm install
      - name: Sincronizar con Capacitor
        run: npx cap sync
      - name: Generar la APK
        run: npx cap build android --no-sync
      - name: Subir el archivo APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-instalable
          path: android/app/build/outputs/apk/debug/app-debug.apk
